### ISSUE TITLE
Когда сборка на линукс? 

### ISSUE THREAD

**Issue by kortaol** [Neodro/NedoRPG_PoStMoDeRn_edishon#1]
Я не буду комментировать общее качество кода (уже сделал это ранее), отсутствие лицензий и .exe файл в самом репозитории (а не во вкладке Releases). 
Короче, ждём сборку на x86_64 Линукс всей Жандармерией

**Comment by wfclCamelCase** [comment]
> Я не буду комментировать общее качество кода (уже сделал это ранее), отсутствие лицензий и .exe файл в самом репозитории (а не во вкладке Releases). 
> Короче, ждём сборку на x86_64 Линукс всей Жандармерией 

Собери сам, свекло по акции

**Comment by kortaol** [comment]
> > Я не буду комментировать общее качество кода (уже сделал это ранее), отсутствие лицензий и .exe файл в самом репозитории (а не во вкладке Releases).
> > Короче, ждём сборку на x86_64 Линукс всей Жандармерией
> 
> Собери сам, свекло по акции

Положим, я и соберу. Вот только мейнтейнить кроссплатформенную поддержку библиотек (при добавлении) мейнтейнер не будет. Да и в принципе ему полезно, как-никак _"Планетарии всех стран, соединяйтесь!"_

**Comment by wfclCamelCase** [comment]
> > > Я не буду комментировать общее качество кода (уже сделал это ранее), отсутствие лицензий и .exe файл в самом репозитории (а не во вкладке Releases).
> > > Короче, ждём сборку на x86_64 Линукс всей Жандармерией
> > 
> > Собери сам, свекло по акции
> 
> Положим, я и соберу. Вот только мейнтейнить кроссплатформенную поддержку библиотек (при добавлении) мейнтейнер не будет. Да и в принципе ему полезно, как-никак _"Планетарии всех стран, соединяйтесь!"_

Каких библиотек, тут только isotream, а новые вряд ли будут, будет только ржение

**Comment by kortaol** [comment]
ГООООООЛ + **\*\*[ЦЕНЗУРОGUN]\*\*** armed

**Comment by Neodro** [comment]
Вы че ебанутые

**Comment by Neodro** [comment]
Вбыдло
